---
title: "The RCP8.5 Issues & Comments"
author: " @PietroMonticone "
date: "`r Sys.Date()`, #ClimateTwitter #EnergyTwitter"
output:
 prettydoc::html_pretty:
    theme: cayman
    highlight: github
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

# Issues

1. *Emissions Narratives $\neq$ Emissions $\neq RF \neq T$ $\neq$ Impacts*

1. *Narratives for $SSP5-RCP8.5$ are too fossil-heavy given current best estimate for $BAU$*

1. *$RF(2100)\approx 8.5 W/{m^2}$ is very unlikely*

1. *$RF_{RCP8.5}$ shouldn't be used as no-policy baseline*

1. *$U_{\text{modellers }}(RF\gg RF_{BAU}) > U_{\text{policymakers }}(RF\gg RF_{BAU})$ ^[e.g. to test and compare models, to explore impacts, etc.]*

1. *$\Delta T_{BAU}(\geq 2100) \approx \Delta T_{RCP8.5}(2100)$ for plausible values of sensitivity ^[$BAU \in$ \{ $IEA$, [Hausfather](https://twitter.com/hausfath) \& [Ritchie](https://twitter.com/jritch) \}]*

1. *$RCP8.5$-based results can be scientifically valid and policy-relevant, despite $\textit{EnergyUse}_{RCP8.5} \neq \textit{EnergyUse}_{BAU}$*

1. *Impacts consistent with $\Delta T_{RCP8.5}(2100)$ are not precluded by $BAU$*

1. *Claiming that RCP8.5-based studies are part of a scare tactic by scientists/media is a baseless conspiracy theory that has no place in adult conversation*

1. *Climate assessments should be well supported with robust communications and outreach resources*

# Comments 

### Pietro Monticone 
>
* When I find a little more time I'll try my best. At the moment with a very simple CMIP3-C4MIP (IPCC AR4) scenario exploration ( ECS $\in$ [3,4] ; CCF $\in$ {1,2} ) I've not been able to reach neither $8.5W/{m^2}$ nor 5°C starting from RCP6 assumptions. ([Source](https://twitter.com/PietroMonticone/status/1204848964660584452?s=20))
* The climate problem is full of intricacies and  counterintuitive features, but I find pretty hard to understand how even something as basic as reference/baseline/no-policy/no-additional-mitigation scenarios could become such a hot topic. ([Source](https://twitter.com/PietroMonticone/status/1207669885108703233?s=20))
* [This](https://twitter.com/PietroMonticone/status/1207689764029243392?s=20) is the only serious, practical problem worth discussing. ([Source](https://twitter.com/PietroMonticone/status/1207703612476002305?s=20))
* Hard to disagree with [Roger's] "impacts and mitigation should not be compared in this way, since the scenarios represent different worlds". See [RCP Overview](https://link.springer.com/article/10.1007/s10584-011-0148-z) and [RCP Database](https://t.co/2rWCKS1BZk?amp=1). ([Source](https://twitter.com/PietroMonticone/status/1207721632502034432?s=20))
* [Title](https://pbs.twimg.com/media/EMPwjWiW4AAfxTH?format=jpg&name=large) with "under high end climate change scenarios"; [Abstract](https://pbs.twimg.com/media/EMPwjWrWkAEqac0?format=jpg&name=large) with ["under high end climate change scenarios"](https://pbs.twimg.com/media/EMPwjWlXYAAb8KA?format=png&name=900x900); Quote marks for BAU; Super cool physics all over the place; High epistemic relevance, maybe less policy-relevance. Nothing embarassing here, just great science. ([Source](https://twitter.com/PietroMonticone/status/1208073635082260481?s=20))
* I strongly believe we should try to condense what really matters in a bunch of clear, accurate points of convergence. Otherwise it would be extremely hard to see what we could possibly mean by progress in this conversation. ([Source](https://twitter.com/PietroMonticone/status/1208542046895693825?s=20))
* I'll try to include that in a quasi-formal suit of clear, unambiguous propositions in order to minimize misinterpretations, foster productive discussion and eventually policy-relevant convergence. ([Source](https://twitter.com/PietroMonticone/status/1208779678393262082?s=20))
* "RCP8.5≠BAU" might not be so irrelevant for amelioration impact literature (e.g. [solar geoengineering](https://t.co/VQXnsunJq3?amp=1)). ([Source](https://twitter.com/PietroMonticone/status/1208434906868654081?s=20))

### Zeke Hausfather 
>
* Climate change is more a problem of degrees than thresholds. While we should try and meet ambitious targets, we also shouldn't give in to despair if we cannot get our political and societal act together fast enough. Avoiding a 2C+ world is important even if we pass 1.5C. ([Source](https://twitter.com/hausfath/status/1210259423156789248?s=20))
* [We ough to] communicate better about the role (and relative likelihood) of different scenarios. I think in the last year there has been a lot of progress on this (annoyingly endless twitter arguments notwithstanding). ([Source](https://twitter.com/hausfath/status/1207723770074451968?s=20))
* The design of the SSPs in theory makes it easier to compare across scenarios (since you have multiple mitigation pathways using the same SSP). In practice, since the CMIP6 scenarios pick different SSPs for each pathway (except SSP1 which gets 1.9 and 2.6) this is challenging. ([Source](https://twitter.com/hausfath/status/1207722585422589952?s=20))
* You can compare scenarios across different SSPs as long as you account for their different socioeconomic drivers (population, GDP, assumptions around technology innovation/transfer, etc.). ([Source](https://twitter.com/hausfath/status/1207728266749992963?s=20))
*  It would take another 100 years of flat current emissions after 2100 to get to RCP8.5-levels of forcing... (but the system will be closer to equilibrium after 2100, so you'd have a bit higher temps  all things being equal). ([Source](https://twitter.com/hausfath/status/1210977229368225798?s=20))
* Using a TCRE approach you'd still end up with mean expected RCP8.5 temps around 2200, but I'm not sure how well the cumulative CO2/warming relationship holds up over 180 years (vs 80). ([Source](https://twitter.com/hausfath/status/1210985718597636096?s=20))
* If climate sensitivity is high you could end up with lower-end RCP8.5 temps (~4C) under a RCP6.0 type scenario by 2100. But I suspect using a subset of high sensitivity RCP6 models to simulate this might be more useful than using all RCP8.5 runs as a proxy. ([Source](https://twitter.com/hausfath/status/1210986425736290304?s=20))
* There are other reasons to have RCP8.5 (e.g. worse than BAU emissions coupled with large carbon cycle feedbacks), but I'm skeptical of using it as a proxy for high sensitivity outcomes as sensitivity uncertainty and emissions uncertainty are orthogonal by construction. ([Source](https://twitter.com/hausfath/status/1210986895586410502?s=20))


### Auke Hoekstra
> 
* I have the impression there are many in the climate community that resist the idea of expressing relative probabilities. Am I wrong? Is this changing? ([Source](https://twitter.com/AukeHoekstra/status/1207743057493471232?s=20))
* Reformulate 3. as "RCP8.5 is very unlikely" ([Source](https://twitter.com/AukeHoekstra/status/1209010954278756352?s=20))
* Add "RCP 8.5 should never be used in any SSPs but SSP5" ([Source](https://twitter.com/AukeHoekstra/status/1209012725931794433?s=20))
* Reformulate 4. as "RCP 8.5 should not be used as a no policy baseline in SSP 5 and should never be used in SSP1-4" ([Source](https://twitter.com/AukeHoekstra/status/1209012725931794433?s=20))
* Bottom line for me: let's stop trying to create fights where they are not useful and let's start to think how we can give AR6 more papers with a realistic BAU so AR6 gives policy makers a good grasp of what can be achieved by mitigation. ([Source](https://twitter.com/AukeHoekstra/status/1209004859476905985?s=20))
* As long as climate scientists are aware they don't know very much of the energy system and accept predictions of people who do and label their energy inputs accordingly all is fine. Or should energy people start picking forcings they like because climate predictions are unsure? ([Source](https://twitter.com/AukeHoekstra/status/1209404521224572928?s=20))
* And since most people accept AGC by now and sensitivities haven't changed much (1.5-4.5 per doubling of CO2) the focus should now shift to energy systems I think. Simply extending them with sensitivities gives policy makers the temperature increase for each energy scenario. ([Source](https://twitter.com/AukeHoekstra/status/1209406950322196480?s=20))
* That way climate scientists can run any scenario they like without having to worry someone will question how likely or unlikely that is because that is now a question you can answer by running energy models. Also more interesting for policy makers since there they can influence. ([Source](https://twitter.com/AukeHoekstra/status/1209407502326087681?s=20))
* Looking at climate scientists to answer the question of "how much global warming will we get?" is outdated. That question must be answered by people making predictions about how much fuel we will burn and what food we will eat. That's my take away of this discussion. ([Source](https://twitter.com/AukeHoekstra/status/1209409306061344768?s=20))
* I wish climate scientist would stop giving opinions about the energy system when they know so little about it. The energy system is changing so you can't use past technology and emissions and project into the future. Also people want wealth, not carbon credits. ([Source](https://twitter.com/AukeHoekstra/status/1209505189507543040?s=20))
* You saw the [emissions per person](https://pbs.twimg.com/media/EMbLhlvWsAE0URn?format=jpg&name=large) of Peters? There really is no plausible scenario to 8.5 emissions that would be taken seriously in the energy community. For reasons unclear to me that is an unpopular message but it's true nontheless. For me it's a huge Christmas present. ([Source](https://twitter.com/AukeHoekstra/status/1209500195806990336?s=20)


### Michael Liebreich
>
* Convene a research review, to look at all papers which use RCP8.5 explicitly or implicitly as BAU, or which compare it inappropriately with other SSPs. Triage into OK; needs new abstract and press release; must be withdrawn and corrected. And beer, we definitely gonna need beer! ([Source](https://twitter.com/MLiebreich/status/1207746005036351489?s=20))
* This is the heart of the discussion. RCP8.5 was originally based on massive coal growth. That is now seen as wildly improbable, but the climate community, many of whom think of RCP8.5 as BAU, still wants to keep using it despite failing to produce a plausible alternative pathway. ([Source](https://twitter.com/MLiebreich/status/1208886789378850816?s=20))
* The fact is, coal use in the global power system has been flat since 2012. Preliminary figures say it dropped 3% in 2019. Hurrah! ([Source](https://twitter.com/MLiebreich/status/1209801992882806787?s=20))
* In many ways climate diplomacy will look very similar in 2030 to today: consensus around the need for action, a growing body of rules, an increasing level of ambition and commitment, but a high level of frustration at the inadequate rate of progress. ([Source](https://twitter.com/MLiebreich/status/1209876260438065153?s=20))
* While climate diplomacy may still look similar in 2030, climate science will not. Sadly, we will have had to give up hope of keeping to 1.5C of temperature increase. But the catastrophism of the last few years will have passed too. ([Source](https://twitter.com/MLiebreich/status/1209883104464318470?s=20))
* It turns out that the most catastrophic climate outcomes, ubiquitously described as baseline or business-as-usual by climate scientists, journalists and activists, are not where we are headed, but represent an extreme and highly implausible scenario. ([Source](https://twitter.com/MLiebreich/status/1209883781496233986?s=20))
* If you want to know what BAU refers to, it's not easy to figure out, because it is only defined as "baseline". Nowhere will you find it formally defined as RCP8.5. ([Source](https://twitter.com/MLiebreich/status/1209887314735972357?s=20))
* But what you will find - repeated throughout the report of Working Group III of the 5th Assessment Report - is a chart that shows 'baseline' (the term for the set of no-mitigation runs) is largely congruent with RCP8.5, and baseline's median can only be achieved using RCP8.5. ([Source](https://twitter.com/MLiebreich/status/1209888405557063680?s=20))
* So 'baseline' is - to all intents and purposes - inseparable from RCP8.5, and BAU is quite explicitly described as being identical to 'baseline'. ([Source](https://twitter.com/MLiebreich/status/1209889902315356161?s=20))
* So although the IPCC never _explicitly_ says anyone should use RCP8.5 as business-as-usual, it certainly frames RCP8.5 as business-as-usual, and provides no other no-mitigation scenario that can be used instead. ([Source](https://twitter.com/MLiebreich/status/1209890063565426688?s=20))
* When RCP 8.5 was originally developed, it was described as "a relatively conservative business as usual case with low income, high population, and high energy demand." And that energy demand is met in RCP 8.5 by coal. Lots of coal. Lots and lots of coal. ([Source](https://twitter.com/MLiebreich/status/1209908798384685057?s=20))
* At the time it was developed, in 2011, maybe RCP8.5 looked justified, because of recent surging emissions, driven by the industrialisation of China. But now the 7x increase in coal use per capita by 2100 in RCCP8.5 looks ludicrous. ([Source](https://twitter.com/MLiebreich/status/1209910799675875334?s=20))
* In 2017 [Ritchie and Dowlatabadi](https://t.co/NFVI7G792s?amp=1) showed why "vast expansion in 21st-century coal consumption should not be used to describe any plausible reference case of the global energy future." Basically there's not enough economically recoverable coal in the ground! ([Source](https://twitter.com/MLiebreich/status/1209915445131857921?s=20))
* We all know IEA scenarios have been too pessimistic about clean energy, ever since I founded NEF. Yet even IEA's Current Policy Scenario tracks way below RCP 8.5 through to 2040. Famously pessimistic energy experts are more optimistic than 99% of IPCC scenarios! ([Source](https://twitter.com/MLiebreich/status/1209917169192112128?s=20))
* To reach RCP8.5 levels of radiative forcing by 2100, atmospheric CO2 would need to reach 1,100 ppm (315ppm in 1959, it's 411 ppm today). Extrapolating linearly gets to 540ppm. Adjust for recent acceleration in rate of increase, and you get about 650ppm. ([Source](https://twitter.com/MLiebreich/status/1209918415680548864?s=20))
* What about feedbacks? The difference between 650ppm and 1,100ppm by 2100 would require the release of many hundreds of gigatons more CO2. There are no feedbacks I have found in the literature that can deliver this amount in the 80 years between now & 2100. ([Souece](https://twitter.com/MLiebreich/status/1209919219787354117?s=20))
* It is legitimate to worry about feedbacks and tipping points, but NOT legitimate to model them using an implausible concentration scenario for 2100. Give unto 2100 what is 2100s! For century time horizons, Real Options probably beat the precautionary principle. ([Source](https://twitter.com/MLiebreich/status/1209921210391371777?s=20))
* The world of RCP 4.5 is an ugly place, with warming of 2.0C to 4.5C by 2100. We absolutely must bend the arc towards the lower end of that range, or below. But it's not the 3.3 to 7.4C of RCP8.5, which generate most of the news stories. ([Source](https://twitter.com/MLiebreich/status/1209926134344888320?s=20))
* If we have to act just as urgently, why does any of this matter? First, a robust coalition for climate action can only be built on bullet-proof science. When IPCC Assessment Report (AR6) appears in 2022, it cannot rest on implausible scenarios. ([Source](https://twitter.com/MLiebreich/status/1209927541470961664?s=20))
* The second reason to stop depicting RCP 8.5 business-as-usual or baseline is that it is immoral. There may be practical argument for using fear as a motivator for climate action,  but there is a name for using invented fears: it is called populism. ([Source](https://twitter.com/MLiebreich/status/1209928375734865920?s=20))
* If you think I am exaggerating about the moral jeopardy into which some activists have fallen? [Watch](https://youtu.be/6Lt0jCDtYSY) Rupert Read telling a bunch of kids they may not reach adulthood. This would be unethical even if it were what the science said, which it is not. ([Source](https://twitter.com/MLiebreich/status/1209930230477066246?s=20))
* At some point during the next 10 years, it will become clear that RCP 8.5, an utterly terrifying, high-end scenario when it was first mooted in 2007, can no longer be considered plausible, much less BAU. In the parlance, #RCP85isBollox. ([Source](https://twitter.com/MLiebreich/status/1209935411285569537?s=20))
* Growth in emissions will have levelled off, partly because China’s coal-fired surge is over, but also because of the hard work of millions of people around the globe in energy and transport. We should be celebrating that fact, not covering it up. ([Source](https://twitter.com/MLiebreich/status/1209935524594667522?s=20))
* We will be pretty sure we are tracking a medium-range scenario with horrendous climate impacts and huge uncertainty about what happens after 2100. But we have broken the back of the transition and will have line-of-sight to achieving the 2C Paris goal. ([Source](https://twitter.com/MLiebreich/status/1209935692761092096?s=20))
* If I am right, by 2030 we will be starting to see a glimmer of hope at the end of the climate change tunnel. We will have narrowed the range of outcomes, averted the worst, and seen the back of peak emissions. A much better place than where we are today. ([Source](https://twitter.com/MLiebreich/status/1209935803826294784?s=20))
* None of this should be taken as a call to complacency: to the contrary. Some have accused me of bad faith for highlighting the fact that #RCP85isBollox. All I want is to ensure the science base is robust. If not, we risk losing another decade, as we did with #Climategate. ([Source](https://twitter.com/MLiebreich/status/1209937198461665280?s=20))
* You think that is an exaggeration? Remember [those 3000 or more papers](https://t.co/hdsH01fBky?amp=1) describing RCP8.5 as BAU. They are out there in the literature, being cited, perhaps as we speak, in drafts of the IPCC's 2022 Assessment Report. That must not be allowed to happen. ([Source](https://twitter.com/MLiebreich/status/1209938070302339080?s=20))
* And what of the [52 papers](https://t.co/RtoWU73PC1?amp=1) so far published which use a scenario called RCP8.5-SSP3, a chimera which combines radiative forcing of 8.5W/m2 by 2100 with a socioeconomic pathway that cannot plausibly get close to that level. This is not robust science! ([Source](https://twitter.com/MLiebreich/status/1209941747876454400?s=20))
* My big worry is that the IPCC's 6th Assessment Report risks the same problems as the 5th. It has already been decided that ["SSP5-8.5 should be considered the highest priority"](https://www.geosci-model-dev.net/9/3461/2016/gmd-2016-84.pdf) for modellers. The inevitable result is that it will be interpreted as BAU. ([Source](https://twitter.com/MLiebreich/status/1209943613091786752?s=20))
* As I have said, I am confident that by 2030, all these problems will have been resolved; we will have a much better handle on the science and the uncertainties will be more bounded. But I do hope we don't have to wait until 
IPCC Assessment Report 7 in 2028 to get there! ([Source](https://twitter.com/MLiebreich/status/1209944316023656449?s=20))

### Justin Ritchie 
>
* From my perspective, the issue with the RCP design was that it had been well known in previous decades that if there is no BAU, then people will look for a BAU, and therefore we have to be explicit about that because otherwise people use implicit clues to guide them. ([Source](https://twitter.com/jritch/status/1207671030027825152?s=20))
* If we had a truly fresh start creating climate scenarios without any previous anchors, would we still select RCP8.5 as an end point? Or would there still be a fight to justify? A big part of the resistance here must be all the inertia created by 1000s of papers in the literature. ([Source](https://twitter.com/jritch/status/1209526698636652544?s=20))

### Roger Pielke Jr. 
>
* One big problem with $BAU$ is it’s use in $CBA$. Consider if we were to take Zeke & Justin analysis seriously & simply plug it into USNCA, the benefits of mitigation would be zero (obviously wrong). Due to fact that NCA calculated such benefits as impacts avoided/reduced = $BAU$ - $RCP4.5$ . ([Source](https://twitter.com/RogerPielkeJr/status/1207700090439131136?s=20))
* Comparisons across mitigation pathways within particular a SSP makes sense, once you make the leap to comparing across different SSPs things get problematic. ([Source](https://twitter.com/RogerPielkeJr/status/1207723575207063559?s=20))
* The claimed policy relevance of RCP8.5 is not a good argument for its role in IPCC. Maybe it is interesting scientifically, but don’t base claims of its relevance on “plausibility”. ([Source](https://twitter.com/RogerPielkeJr/status/1209288832794808320?s=20))

### Stefan Rahmstorf
>
* I don’t know how common that misunderstanding was, though. I have always presented $RCP8.5$ as the upper end of the range of possible futures. $RCP8.5$ is widely considered very unlikely among climatologists because the economic collapse setting in way before 4 degrees C warming. ([Source](https://twitter.com/rahmstorf/status/1207570677647249409?s=20))

### Richard Betts 
>
* I tend to call it "high emissions scenario" in talks. I've always been uncomfortable with the fact that the actual impacts of climate change are neglected from the emissions scenarios from the IAMs - I can see why it's keeps the analysis simple, but surely it is inconsistent. ([Source](https://twitter.com/richardabetts/status/1207586161469927424?s=20))
* Note that emissions don't need to reach 30 GtC/yr to give RCP8.5 concentrations. If you account for climate-carbon cycle feedbacks, RCP8.5 CO$_2$ concentrations could result from emissions reaching only 20 GtC/yr by 2100 - just double 2019 emissions. See [here](https://journals.ametsoc.org/doi/full/10.1175/JCLI-D-12-00554.1). ([Source](https://twitter.com/richardabetts/status/1209270771572518913?s=20))
* CO$_2$ emissions of 20 GtC/yr by 2100 are not much higher than the upper end of range of  [Hausfather](https://twitter.com/hausfath)'s extended IEA estimates, which is 18.27 GtC. This is 67 GtCO2/yr: convert using $1 GtC = 1 Gt CO2 \times \frac{12}{44}$, ratio of mass of C atom to mass of CO2 molecule. ([Source](https://twitter.com/richardabetts/status/1209274492008181761?s=20))
* I'm not trying to justify RCP8.5 as BAU. I'm just showing that it's not an implausible scenario, and therefore worth looking at. ([Source](https://twitter.com/richardabetts/status/1209279700792729601?s=20))
* We avoid using the term "predictions". Climate projections can be viewed as exploring various _what-if_ scenarios. For example, if everyone on the planet emitted the same as the average American (4.43 tC), that's 34 GtC / yr - above the standard RCP8.5 emissions. See [here](https://cdiac.ess-dive.lbl.gov/trends/emis/top2014.cap). ([Source](https://twitter.com/richardabetts/status/1209416567882162176?s=20))
* Of course that doesn't automatically mean that this is actually possible - but that then raises another angle of the debate, on equity. So one interpretation of RCP8.5 is that it illustrates the climate consequences of an "Everyone emits CO2 like the average American" world. ([Source](https://twitter.com/richardabetts/status/1209417281723387904?s=20))

### Peter Jacobs
>
* All of these can be true: 1. $RCP8.5$ narrative has too much fossil fuels ; 2. $8.5W/m^2$ by exactly 2100 no longer "BAU" ; c) current policy can get us within $RCP8.5$ levels of warming by 2100 or a few decades thereafter. ([Source](https://twitter.com/past_is_future/status/1208246363227598849?s=20))
* I'm seeing a lot of people take points 1. and 2. and use them to argue explicitly/implicitly against 3. , which as far as I can tell is a violent misrepresentation of the evidence available. That doesn't mean we'll necessarily see that much warming! It's just not _precluded_ by current policy/trends. ([Source](https://twitter.com/past_is_future/status/1208247342098456577?s=20))
* The issue is also that there are a huge number of modeling runs available under RCP8.5 that people are using and have already used. If interested in temperature for example, there is no reason to discount those studies based on this revision of BAU energy use. Some advocate this. ([Source](https://twitter.com/past_is_future/status/1209170018702962688?s=20))
* There's been an unfortunate flattening of the dialogue, with people who correctly accept the distinctions between BAU and RCP8.5 but say the latter is still useful vs. those dismissing RCP8.5 as invalid & useless, & arguing for retractions or post hoc edits to papers using it. ([Source](https://twitter.com/past_is_future/status/1209171550815043584?s=20))
* The latter group proudly identify themselves by proclaiming "RCP8.5 is bollocks" despite months of scientists pointing out how unnecessarily reductive this is, especially outside that group's own narrow use cases, and including actual climate modelers and end users. ([Source](https://twitter.com/past_is_future/status/1209172298357456897?s=20))
* If you wrote a paper that uses CMIP5 RCP8.5 temps as an input, you wouldn't have to wait until 2200 to plausibly see those temps, let alone they wouldn't be precluded from happening by current policy, and pretending they're impossible as we've seen some doing is at best ignorant. ([Source](https://twitter.com/past_is_future/status/1210978857660157952?s=20))
* My main point is not as 1:1 substitute for higher sensitivity modeling going forward but whether revision to BAU emissions renders extant work using 8.5 policy irrelevant (it doesn't). ([Source](https://twitter.com/past_is_future/status/1210988048726548480?s=20))


### Ken Rice 
> 
* I think everyone now agrees that RCP8.5 isn't a business as usual scenario.  It seems clear that our future emission pathway is unlikely to be consistent with an RCP8.5 concentration pathway. ([Source](https://twitter.com/theresphysics/status/1207671228116455424?s=20))
* Beyond that I'm not entirely sure what the issues are.  Some seem to object to the use of "business as usual" in any context. Some seem to object to the use of RCP8.5 in any circumstance. Some seem to think the IPCC reports said things they didn't actually say. ([Source](https://twitter.com/theresphysics/status/1207671522472681472?s=20))
* FWIW, as far as I can tell, when the RCPs were first introduced, it may well have been reasonable to use RCP8.5 as a BAU scenario.  This no longer seems to be suitable.  We can't change the past, though. ([Source](https://twitter.com/theresphysics/status/1207671895992213505?s=20))
* From a climate modelling perspective, $RCPs$ are simply concentration, or forcing, pathways.  They can be used to investigate how the climate will respond to different changes in atmosphere CO$_2$ concentration (or forcing). ([Source](https://twitter.com/theresphysics/status/1209138892600938496?s=20))
* Clearly, it's also useful to develop socio-economic pathways that could lead to the various concentration/forcing pathways.  It's become more and more clear that it's very unlikely that we'll follow a $RCP8.5$ pathway (but the same is probably true for $RCP2.6$). ([Source](https://twitter.com/theresphysics/status/1209139199846297600?s=20))
* So, one might then say "climate models should only use pathways that we are likely to follow".  The problem is that there is a range of warming for each pathway (i.e., even along our current $BAU$ pathway, it is something like $1.9°C$ - $4.4°C$). ([Source](https://twitter.com/theresphysics/status/1209139509872537614?s=20))
* The sensitivity of a climate model is emergent (i.e., it's not easy to tune it).  Hence, if one wants to investigate the impact of, for example, $> 4°C$ of warming, one might need to force a climate model with a forcing pathway that is seen as being unrealistically high. ([Source](https://twitter.com/theresphysics/status/1209139850449997824?s=20))
* This doesn't mean that the modellers are assuming that this is a $BAU$ pathway, it simply means that the modellers are investigating the impact of high levels of warming which could happen if we continue along a $BAU$ pathway, but climate sensitivity turns out to be high end. ([Source](https://twitter.com/theresphysics/status/1209140319201169414?s=20))
* That's essentially the point some are trying to make.  It may be very unlikely that we're going to follow an $RCP8.5$ forcing pathway, but since we can't rule out $> 4°C$ of warming along our current $BAU$ pathway, it may still be a useful pathway for climate impact studies. ([Source](https://twitter.com/theresphysics/status/1209140670318989313?s=20))
*  Most research groups will typically use a single climate model, which will have a single climate sensitivity. However, we know that there is an uncertainty in climate senstivity.  Hence if a research group wants to investigate the high levels of warming that might occur under a $BAU$ pathway, they may need to force their model with a higher than BAU forcing pathway. The impacts depends on the temperature change, not directly on the change in forcing. ([Source](https://twitter.com/theresphysics/status/1209146817776148480?s=20))
* If we want to explore the impacts of $> 4°C$ with a model known to have a low climate sensitivity, then we may need to use a higher than $BAU$ forcing pathway. ([Source](https://twitter.com/theresphysics/status/1209148009143033856?s=20))

### Ken Caldeira 
>
* $RCP8.5$ is useful for understanding what might happen if emissions exceed current projections. ([Source](https://twitter.com/KenCaldeira/status/1209201769659527168?s=20))
* Year 2100 CO2 emissions in RCP8.5 are abut 30 GtC/yr, about 3 times greater than in 2020. Year 2020 CO2 emissions will be nearly 8 times greater than  in 1940, 80 years ago. ([Source](https://twitter.com/KenCaldeira/status/1209201769659527168?s=20))
* In $RCP8.5$, in the 80 years between 2020 and 2100, CO2 emissions increase on average by about 1.4%/yr. Historically, in the 80 years between 1940 and 2020, CO2 emissions increased on average by about 2.6%/yr. ([Source](https://twitter.com/KenCaldeira/status/1209219111659528193?s=20))
* For many studies, my preferred scenario is abrupt 4x CO$_2$ because it clearly demonstrates modeled climate response without implying anything about likelihood of different emissions scenarios in the real world. ([Source](https://twitter.com/KenCaldeira/status/1209219586672885760?s=20))
* Good experimental design might mean that the scenarios that should be simulated the most would be the ones with the highest signal-to-noise ratio. The controversy is not about simulating the scenarios. It is about interpreting the results as most-likely no-policy outcomes. ([Source](https://twitter.com/KenCaldeira/status/1209225120750817280?s=20))
* The cumulative net emissions in RCP8.5 to year 2100 would represent a dramatic decrease in long-term CO2 emissions trends. These cumulative emissions cannot be ruled out as a plausible business-as-usual scenario, even if it is not our central expectation. ([Source](https://twitter.com/KenCaldeira/status/1209238346209189888?s=20))

### Glen Peters 
> 
* From speaking to people, it seems RCP8.5 is important because of 1) continuity with previous CMIPs & 2) high signal-to-noise. But, one will never find this written. It doesn't explain why 8.5 is selected, which I think is frankly bizarre given some of the authors. ([Source](https://twitter.com/Peters_Glen/status/1160158928476487680?s=20))
* As many argue, RCP8.5 is chosen because it envelopes extremes. Fair enough. That sounds & looks plausible. However, one does not need to dig to far to find what [that](https://pbs.twimg.com/media/EBm2s6bW4AAItIv?format=jpg&name=large) means. ([Source](https://twitter.com/Peters_Glen/status/1160159268299055106?s=20))
* [Here](https://pbs.twimg.com/media/EBm3K-hWwAIlPeF?format=jpg&name=large) is what coal does in those scenarios. Of course, there is oil & gas. But, either way, to get to such high CO2, in the world we live today, is quite a task. So, when you say RCP8.5 is plausible, then you are implicitly accepting these pathways. ([Source](https://twitter.com/Peters_Glen/status/1160159786702397440?s=20))
* Even the people that developed these scenarios think RCP8.5 is crazy, not just for the RCP part, but because it is SSP5, which has low challenges to adaptation. That is, we can adapt. See [here](https://www.sciencedirect.com/science/article/pii/S0959378016300681?via%3Dihub). ([Source](https://twitter.com/Peters_Glen/status/1160160430855270400?s=20))
* Despite CO$_2$ emissions growing a factor of 10 since 1870, per capita emissions have grown a factor of 2. Per capita emissions have been flat since 1950, except for the Chinese growth in the 2000s. What would cause per capita emissions to grow in the future? ([Source](https://twitter.com/Peters_Glen/status/1209024593178038273?s=20))
* Take out land-use change, & increases in per capita emissions have come with new fossil sources. What is the next fossil source in increase per capita emissions? Will gas add to coal & oil, or displace it? Will non-fossil source displace fossil sources? ([Source](https://twitter.com/Peters_Glen/status/1209027198629371906?s=20))
* $RCP8.5$ (& some other no policy baselines) require CO$_2$ emissions per capita to double by 2050 & triple by 2100, despite being flat for the last 50 years & only doubling since 1900. RCP8.5 is without historical precedent. ([Source](https://twitter.com/Peters_Glen/status/1209028367774814208?s=20))
* Another way to put it, is that $RCP8.5$ assumes that coal grows faster than population. History shows that is rare. If emissions per capita remained at about 6, and population went to 10 billion (high end), then emissions would be 60GtCO2/yr, far lower than RCP85. ([Source](https://twitter.com/Peters_Glen/status/1209048300550283269?s=20))
* If population grows to 10 billion (sort of high-end), & CO$_2$ per capita remains at 6tCO$_2$/person (a little higher than the long-term trend), then emissions would reach 60GtCO$_2$/yr. $RCP8.5$ >120GtCO₂/yr. ([Source](https://twitter.com/Peters_Glen/status/1209059892176334848?s=20))
* To believe #RCP85 you need: world that prioritises fossil fuels; zero climate policy to 2100; zero climate impacts to 2100. See [here](https://t.co/1qPPw6ZTqT?amp=1). ([Source](https://twitter.com/Peters_Glen/status/1209387352013103106?s=20))
* There are many good things about SSPs. But, there are also weaknesses. The biggest issue is one of communication. Integrated Assessment Modellers know this stuff inside out, but very few know the specifics. And, I would argue, this is why there are perceived "black boxes", etc. ([Source](https://twitter.com/Peters_Glen/status/1209405058720444417?s=20))
* SSP framework has advantages and disadvantages, I am happy to acknowledge both, and I happy to use (and do) the framework knowing the issues. I think RCP85 is infeasible and for a variety of reasons __I__ would not use it (or use in very restrictive contexts). ([Source](https://twitter.com/Peters_Glen/status/1209461444703670273?s=20))

### Edwards Byers
>
* I'd say we're currently on SSP3, with high inequalities, whereas all emitting like Americans would be SSP5. See [here](https://www.iiasa.ac.at/web/home/about/events/7.SSPNarratives_IIASA_BvR.pdf). ([Source](https://twitter.com/EdwardByers/status/1209423911500300288?s=20))


### Andrew Dessler 
> 
* With the new result that warming will likely be in the neighborhood of 3°C on a business-as-usual trajectory, I suspect skeptics’ next argument will be “3 deg C is warming is not so bad”. ([Source](https://twitter.com/AndrewDessler/status/1208808204970397702?s=20))
* Don’t fall for this. Remember: we’ve had about 1° of warming so far and the impacts are already severe. And the damages are non-linear, so the damage at 3° is a lot worse than 3x than the damage at 1°. ([Source](https://twitter.com/AndrewDessler/status/1208808206958510081?s=20))
* One more thought: when "business-as-usual" was 4-5 deg C of warming over this century, limiting warming to 2 deg seemed impossible.  But if b-a-u is now 3 deg C, then it seems to me that 2 deg C is now possible with strong action.  That, I think, is the real hopeful message here. ([Source](https://twitter.com/AndrewDessler/status/1209505329093984258?s=20))
* If you're investigating, say, the forced response of sea ice to climate change, you want to drive your model with a scenario with A LOT of forcing so it dominates internal variability, yielding the biggest signal-to-noise ratio for the response. This is why you'd use RCP8.5 . ([Source](https://twitter.com/AndrewDessler/status/1209671361225998338?s=20))
* I've been thinking how to communicate the big new result that emissions have been revised downward, leading to less warming: 3°C. Here is my analogy: "Good news, everyone! Your firing squad is only going to have 4 riflemen rather than the 6 originally scheduled. You're welcome!" ([Source](https://twitter.com/AndrewDessler/status/1210837488941617152?s=20))




# Glossary

* $BAU$: "Business-As-Usual"

* $CBA$: "Cost-Benefit Analysis"

* $RF$: "Radiative Forcing"

* $RCPX$: "Representative Concentration Pathway with $RF(2100)\approx X$"

* $RCP8.5$: 

     * Developed by the MESSAGE modeling team and the IIASA Integrated Assessment Framework at the International Institute for Applies Systems Analysis (IIASA), Austria. 
     * Characterized by increasing greenhouse gas emissions over time representative for scenarios in the literature leading to high greenhouse gas concentration levels. 
     * The underlying scenario drivers and resulting development path are based on the A2r scenario detailed in [Riahi et al. (2007)](https://www.sciencedirect.com/science/article/pii/S0040162506001387?via%3Dihub).

* $SSP$: "Shared Socioeconomic Pathway"

* $T$: "Temperature"

* $U$: "Utility"