---
title: "The RCP8.5 References"
author: " @PietroMonticone "
date: "`r Sys.Date()`, #ClimateTwitter #EnergyTwitter"
output:
 prettydoc::html_pretty:
    theme: cayman
    highlight: github
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

## Articles & Blog Posts

#### John Nielsen-Gammon
* [What Is Business As Usual?](http://climatechangenationalforum.org/what-is-business-as-usual/)

#### Henrik Carlsen et al. 
* **2017** [Transparent scenario development, Nature Climate Change](https://www.nature.com/articles/nclimate3379)

#### Roger Pielke Jr. 
* [Opening Up the Climate Policy Envelope](https://issues.org/opening-up-the-climate-policy-envelope/)
* [The Incredible Story Of How Climate Change Became Apocalyptic](https://www.forbes.com/sites/rogerpielke/2019/12/06/the-incredible-story-of-how-climate-change-became-apocalyptic/)
* [In 2020 Climate Science Needs To Hit The Reset Button, Part 1](https://www.forbes.com/sites/rogerpielke/2019/12/22/in-2020-climate-science-needs-to-hit-the-reset-button-part-one/#35415707482c)
* [In 2020 Climate Science Needs To Hit The Reset Button, Part 2](https://www.forbes.com/sites/rogerpielke/2019/12/23/in-2020-climate-science-needs-to-hit-the-reset-button-part-two/)


#### Zeke Haufather
* [Carbon Brief Explainer: How ‘Shared Socioeconomic Pathways’ explore future climate change](https://www.carbonbrief.org/explainer-how-shared-socioeconomic-pathways-explore-future-climate-change)
* [Carbon Brief Explainer: The high-emissions ‘RCP8.5’ global warming scenario](https://www.carbonbrief.org/explainer-the-high-emissions-rcp8-5-global-warming-scenario)
* [Carbon Brief Explainer: How scientists estimate ‘climate sensitivity’](https://www.carbonbrief.org/explainer-how-scientists-estimate-climate-sensitivity)

#### CICERO
* [A Guide to Representative Concentration Pathways](https://www.cicero.oslo.no/en/posts/news/a-guide-to-representative-concentration-pathways)

#### Zeke Haufather & Justin Ritchie 
* [A 3C World Is Now “Business as Usual”](https://thebreakthrough.org/issues/energy/3c-world)

#### Michael Liebreich
* [Climate Wars Episode IV – a New Hope for the 2020s?](https://about.bnef.com/blog/in-climate-wars-episode-4-the-2020s-will-bring-new-hope/)

#### David Wallace-Wells
* [We’re Getting a Clearer Picture of the Climate Future — and It’s Not as Bad as It Once Looked](http://nymag.com/intelligencer/2019/12/climate-change-worst-case-scenario-now-looks-unrealistic.html)

#### Noah Smith 
* [Worst Case for Climate Change Doesn’t Look Realistic](https://www.bloomberg.com/opinion/articles/2019-12-23/worst-case-for-climate-change-doesn-t-look-realistic)

#### AXIOS
* [The Decade That Blew Up Energy Predictions](https://www.axios.com/energy-predictions-reality-check-524b9be9-2c0c-407e-86cb-37b11aa72ed2.html)

## Research & Review Papers 

#### Keywan Riahi et al.
* **2007** [Scenarios of long-term socio-economic and environmental development under climate stabilization](https://www.sciencedirect.com/science/article/pii/S0040162506001387?via%3Dihub)
* **2011** [RCP 8.5: A scenario of comparatively high greenhouse gas emissions](https://link.springer.com/article/10.1007/s10584-011-0149-y)

#### Detlef P. van Vuuren et al. 
* **2011** [The Representative Concentration Pathways: An Overview, Climatic Change](https://link.springer.com/article/10.1007/s10584-011-0148-z)

#### Brian C. O’Neill et al.
* **2014** [A New Scenario Framework For Climate Change Research: The Concept of Shared Socioeconomic Pathways, Climatic Change](https://link.springer.com/article/10.1007%2Fs10584-013-0905-2)

#### Brian C. O’Neill et al.
* **2016** [The Scenario Model Intercomparison Project (ScenarioMIP) for CMIP6, Geoscientific Model Development](https://www.geosci-model-dev.net/9/3461/2016/)

#### Nico Bauer et al. 
* **2017** [Shared Socio-Economic Pathways of the Energy Sector: Quantifying the Narratives, Global Environmental Change](https://www.sciencedirect.com/science/article/pii/S0959378016301224)

#### Alexander Popp et al. 
* **2017** [Land-use Futures in The Shared Socio-Economic Pathways, Global Environmental Change](https://www.sciencedirect.com/science/article/pii/S0959378016303399)

#### Justin Ritchie et al.
* **2017** [Why do climate change scenarios return to coal?, Energy, ](https://www.sciencedirect.com/science/article/abs/pii/S0360544217314597)
* **2017** [The 1000 GtC coal question: Are cases of vastly expanded future coal combustion still plausible?, Energy Economics](https://www.sciencedirect.com/science/article/pii/S0140988317301226)
* **2018** [Defining climate change scenario characteristics with a phase space of cumulative primary energy and carbon intensity, Environmental Research Letters, Environmental Research Letters](https://iopscience.iop.org/article/10.1088/1748-9326/aaa494)

## Data
* [RCP Database](http://tntcat.iiasa.ac.at:8787/RcpDb/dsd?Action=htmlpage&page=about)
* [SSP Database](https://tntcat.iiasa.ac.at/SspDb/dsd?Action=htmlpage&page=10)
## Reports & Presentations
#### IPCC 
* [SYR](https://www.ipcc.ch/report/ar5/syr/)
* [WG1](https://www.ipcc.ch/report/ar5/wg1/)
* [WG2](https://www.ipcc.ch/report/ar5/wg2/)
* [WG3](https://www.ipcc.ch/report/ar5/wg3/)

#### IEA 
* [WEO](https://www.iea.org/reports/world-energy-outlook-2019)

#### CAT 
* [Methodology, Current Policy Projections](https://climateactiontracker.org/methodology/current-policy-projections/)

#### AES
* [Climate Scenario Report](https://s2.q4cdn.com/825052743/files/doc_downloads/2018/11/AES_Climate_Scenario_Report111318.pdf)

#### NCAR
* [The Road Ahead: SSP Narratives | Bas van Ruijven](https://www.iiasa.ac.at/web/home/about/events/7.SSPNarratives_IIASA_BvR.pdf)

####  Forum on Scenarios of Climate and Societal Futures: Meeting Report
* [Pardee Center Working Paper, University of Denver](https://pardee.du.edu/sites/default/files/Scenarios%20Forum%20Meeting%20Report%204oct19.pdf)


## Tweets & Threads

#### Justin Ritchie 
* [IEA vs IPCC 1](https://threadreaderapp.com/thread/1196482571443425280.html)
* [IEA vs IPCC 2](https://threadreaderapp.com/thread/1199729350330839042.html?refreshed=yes)
* [IEA vs IPCC 3](https://threadreaderapp.com/thread/1204113683728592897.html)

#### Glen Peters
* [New BAU](https://threadreaderapp.com/thread/1207583078543233024.html)
* [RCP8.5 is without historical precedent](https://twitter.com/Peters_Glen/status/1209028367774814208)
* [SSPs, RCP8.5 and Climate Impacts](https://threadreaderapp.com/thread/1209387352013103106.html?refreshed=yes)

#### Zeke Hausfather 
* [RCP8.5 vs. BAU](https://threadreaderapp.com/thread/1164189973664264192.html?refreshed=yes)
* [New BAU 1](https://threadreaderapp.com/thread/1207355805378342913.html)
* [New BAU 2](https://threadreaderapp.com/thread/1209172698657509376.html)

#### Roger Pielke Jr. 
* [Climate Science Needs a Reset](https://threadreaderapp.com/thread/1209118418827272197.html?refreshed=yes)
* [Climate Scenario Popularity 1](https://threadreaderapp.com/thread/1204087486697234432.html)
* [Climate Scenario Popularity 2](https://threadreaderapp.com/thread/1204497767659261952.html)

#### Michael Liebreich
* [Peak Emissions, Coal Use & RCP8.5](https://threadreaderapp.com/thread/1209761395996266496.html)

#### Jonathan Foley
* [New BAU](https://threadreaderapp.com/thread/1208496927400026112.html)

#### David Wallace-Wells
* [New BAU](https://threadreaderapp.com/thread/1208845752769941510.html)


## Videos

* [Revisiting Business-As-Usual | Justin Ritchie](https://youtu.be/HKK3GjI3_eE)
* [Revisiting Worst-Case Climate Scenarios: Is RCP8.5 Still Plausible? | Justin Ritchie](https://youtu.be/w1YO95nXPVw)

* [Achievements & Needs for Climate Change Scenarios Framework | Brian O’Neill at IAMC2019](https://www.youtube.com/watch?v=0oHcfcFCjrE&feature=youtu.be)

* [Global Carbon Budget 2019: Emissions & Sinks | Glen Peters at COP25](https://youtu.be/ix83a2Y-9uI)
* [Greenhouse Gases in the Atmosphere: Sources, Sinks and Climate Impact | IPCC-WMO at COP25](https://youtu.be/Jq8Arw6wfLA)
* [The Global Carbon Budget & Remaining CO₂ Emissions at COP25](https://youtu.be/S3zioeFrF2A)
* [The Carbon Bucket for 1.5°C](https://youtu.be/XcEyJqluMEU)
* [Climate Extremes & Emissions Gap | euronews at COP25](https://youtu.be/ZY2Wmfqkw6k)

* [The IPCC Sixth Assessment Report at COP25](https://youtu.be/D2QXlrcHxjw)

* [Climate Tipping Points: What They Are & How To Avoid Them | Met Office at COP25](https://youtu.be/hIEO-5DiVqo)





